# What is "concept ID"?

In the AIREADI dataset, OMOP concept IDs are assigned to various variables such as HbA1c, visual acuity, and answers to questionnaires for standardization purposes. For more details, see the OMOP Clinical Data Structure documentation: https://docs.aireadi.org/docs/1/dataset/clinical-data/OMOP-Clinical-Data-Structure/. Finding concept IDs is essential when searching for specific values.

To explore which values are included, you can refer to the OMOP Mapping Table for clinical data (https://docs.aireadi.org/v1-omopTable) or the Data Domain Table for clinical lab tests (https://docs.aireadi.org/v1-dataDomainTable).

# How to find concept IDs?

To identify concept IDs, you can use files such as condition_occurrence.csv, measurement.csv, and observation.csv within the clinical_data section of the dataset.

Here are example codes of finding concept IDs.

In [1]:
import os
import stat

from tqdm import tqdm

import time
import pandas as pd

In [2]:
# custom path -- change to match your file structure
data_root =  r'path/to/your/AIREADI/'  # change this to your own path - one example
data_root = "C:\\Users\\preet\\Documents\\AI_READI\\"  # change this to your own path - another example

In [3]:
# Load clinical data from TSV and CSV files
participants_df = pd.read_csv(data_root + 'participants.tsv', sep='\t')
measurement_df = pd.read_csv(os.path.join(data_root, "clinical_data", "measurement.csv"))
condition_occurrence_df = pd.read_csv(os.path.join(data_root, "clinical_data", "condition_occurrence.csv"))
observation_df = pd.read_csv(os.path.join(data_root, "clinical_data", "observation.csv"))

In [4]:
for df in [participants_df,measurement_df,condition_occurrence_df,observation_df]:
    print(df.shape)
    print(df.columns)
    #print(df.head())

(1067, 15)
Index(['participant_id', 'clinical_site', 'study_group', 'age',
       'study_visit_date', 'recommended_split', 'cardiac_ecg', 'clinical_data',
       'environment', 'retinal_flio', 'retinal_oct', 'retinal_octa',
       'retinal_photography', 'wearable_activity_monitor',
       'wearable_blood_glucose'],
      dtype='object')
(114807, 25)
Index(['measurement_id', 'person_id', 'measurement_concept_id',
       'measurement_date', 'measurement_datetime', 'measurement_time',
       'measurement_type_concept_id', 'operator_concept_id', 'value_as_number',
       'value_as_concept_id', 'unit_concept_id', 'range_low', 'range_high',
       'provider_id', 'visit_occurrence_id', 'visit_detail_id',
       'measurement_source_value', 'measurement_source_concept_id',
       'unit_source_value', 'unit_source_concept_id', 'value_source_value',
       'measurement_event_id', 'meas_event_field_concept_id',
       'qualifier_concept_id', 'qualifier_source_value'],
      dtype='object')
(5902, 16)
Index(['condition_occurrence_id', 'person_id', 'condition_concept_id',
       'condition_start_date', 'condition_start_datetime',
       'condition_end_date', 'condition_end_datetime',
       'condition_type_concept_id', 'condition_status_concept_id',
       'stop_reason', 'provider_id', 'visit_occurrence_id', 'visit_detail_id',
       'condition_source_value', 'condition_source_concept_id',
       'condition_status_source_value'],
      dtype='object')
(279265, 21)
Index(['observation_id', 'person_id', 'observation_concept_id',
       'observation_date', 'observation_datetime',
       'observation_type_concept_id', 'value_as_number', 'value_as_string',
       'value_as_concept_id', 'qualifier_concept_id', 'unit_concept_id',
       'provider_id', 'visit_occurrence_id', 'visit_detail_id',
       'observation_source_value', 'observation_source_concept_id',
       'unit_source_value', 'qualifier_source_value', 'value_source_value',
       'observation_event_id', 'obs_event_field_concept_id'],
      dtype='object')

In [5]:
participants_df.head()

,participant_id,clinical_site,study_group,age,study_visit_date,recommended_split,cardiac_ecg,clinical_data,environment,retinal_flio,retinal_oct,retinal_octa,retinal_photography,wearable_activity_monitor,wearable_blood_glucose
0,1001,UW,pre_diabetes_lifestyle_controlled,69,2023-07-27,train,True,True,True,True,True,True,True,False,True
1,1002,UW,healthy,69,2023-08-01,train,True,True,True,True,True,True,True,False,True
2,1003,UW,oral_medication_and_or_non_insulin_injectable_...,82,2023-08-02,train,True,True,True,True,True,True,True,False,True
3,1004,UW,oral_medication_and_or_non_insulin_injectable_...,61,2023-08-08,val,True,True,True,True,True,True,True,False,True
4,1005,UW,insulin_dependent,58,2023-08-08,val,True,True,True,True,True,True,True,False,True

In [6]:
measurement_df.head()

,measurement_id,person_id,measurement_concept_id,measurement_date,measurement_datetime,measurement_time,measurement_type_concept_id,operator_concept_id,value_as_number,value_as_concept_id,...,visit_detail_id,measurement_source_value,measurement_source_concept_id,unit_source_value,unit_source_concept_id,value_source_value,measurement_event_id,meas_event_field_concept_id,qualifier_concept_id,qualifier_source_value
0,20452,7289,2005200055,2024-05-14,2024-05-14 00:00:00,,32862,0,40.00,0,...,0,"viaosmsf, Snellen fraction - Mesopic VA - OS",0,,0,,0,0,0.0,
1,111043,7043,3017250,2024-02-29,2024-02-29 00:00:00,00:00:00,32856,4172703,28.30,0,...,0,Urine Creatinine (mg/dL),0,mg/DL,0,28.3,0,0,NaN,NaN
2,42372,1102,2005200182,2024-01-09,2024-01-09 00:00:00,,32862,0,10.58,0,...,0,"lbscat_wbc, White Blood Cells (WBC) - x10E3/µL",0,,0,,0,0,0.0,
3,32175,4243,2005200056,2024-06-26,2024-06-26 00:00:00,,32862,0,45.00,0,...,0,"viaodmlog, LLVA Letter Score - Mesopic VA - OD",0,,0,,0,0,45876703.0,Right eye
4,54995,1311,2005200012,2024-06-04,2024-06-04 00:00:00,,32862,0,25.00,0,...,0,"viaodpsf, Snellen fraction - Photopic VA - OD",0,,0,,0,0,0.0,

In [7]:
condition_occurrence_df.head(10)

,condition_occurrence_id,person_id,condition_concept_id,condition_start_date,condition_start_datetime,condition_end_date,condition_end_datetime,condition_type_concept_id,condition_status_concept_id,stop_reason,provider_id,visit_occurrence_id,visit_detail_id,condition_source_value,condition_source_concept_id,condition_status_source_value
0,55,7148,4186898,2023-12-07,2023-12-07 00:00:00,2023-12-07,2023-12-07 00:00:00,45905770,32893,,0,20,0,"mhoccur_plm, Chronic pulmonary (lung) problems (E",0,
1,5364,1120,2005200017,2024-01-24,2024-01-24 00:00:00,2024-01-24,2024-01-24 00:00:00,45905770,32893,,0,1593,0,"mhoccur_rnl, Kidney problems",0,
2,2975,4030,433736,2023-10-10,2023-10-10 00:00:00,2023-10-10,2023-10-10 00:00:00,45905770,32893,,0,863,0,"mhoccur_obs, Obesity",0,
3,2306,7324,46271045,2024-05-28,2024-05-28 00:00:00,2024-05-28,2024-05-28 00:00:00,45905770,32893,,0,678,0,"mhoccur_cns, Other neurological conditions",0,
4,2456,7231,316866,2024-02-20,2024-02-20 00:00:00,2024-02-20,2024-02-20 00:00:00,45905770,32893,,0,710,0,"mhoccur_hbp, High blood pressure",0,
5,2323,7360,317002,2024-06-04,2024-06-04 00:00:00,2024-06-04,2024-06-04 00:00:00,45905770,32893,,0,682,0,"mhoccur_lbp, Low blood pressure",0,
6,2094,7310,201826,2024-05-22,2024-05-22 00:00:00,2024-05-22,2024-05-22 00:00:00,45905770,32893,,0,628,0,"mhterm_dm2, Type II Diabetes",0,
7,2930,4026,4317977,2023-10-10,2023-10-10 00:00:00,2023-10-10,2023-10-10 00:00:00,45905770,32893,,0,851,0,"mhoccur_crt, Cataracts (in one or both eyes)",0,
8,5674,1019,433736,2023-08-21,2023-08-21 00:00:00,2023-08-21,2023-08-21 00:00:00,45905770,32893,,0,1705,0,"mhoccur_obs, Obesity",0,
9,5156,1268,316866,2024-04-28,2024-04-28 00:00:00,2024-04-28,2024-04-28 00:00:00,45905770,32893,,0,1513,0,"mhoccur_hbp, High blood pressure",0,

In [8]:
observation_df.head(10)

,observation_id,person_id,observation_concept_id,observation_date,observation_datetime,observation_type_concept_id,value_as_number,value_as_string,value_as_concept_id,qualifier_concept_id,...,provider_id,visit_occurrence_id,visit_detail_id,observation_source_value,observation_source_concept_id,unit_source_value,qualifier_source_value,value_source_value,observation_event_id,obs_event_field_concept_id
0,44396,7353,2005200128,2024-06-21,2024-06-21 00:00:00,32862,1.0,1.0,36210226,0,...,0,355,0,"pxrd3, On a scale of 1-6, how stressful was this",0,,,,0,0
1,276196,1384,42528764,2024-07-31,2024-07-31 00:00:00,37161934,17.0,17.0,0,0,...,0,0,0,years_of_education,0,NaN,NaN,17.0,0,0
2,210536,1053,40766232,2023-10-10,2023-10-10 00:00:00,32862,18.0,18,45884155,0,...,0,1613,0,"pxed1, What is the highest grade or level of scho",0,,,,0,0
3,197490,1268,2005200504,2024-05-01,2024-05-01 00:00:00,32862,4.0,4.0,0,0,...,0,1513,0,"pxrd15, On a scale of 1-6, how stressful was this",0,,,,0,0
4,168986,4239,2005200014,2024-02-24,2024-02-24 00:00:00,32862,0.0,0.0,45878245,80502,...,0,1298,0,"mhoccur_oa, Osteoporosis",0,,Osteoporosis,,0,0
5,70439,7222,4078999,2024-02-03,2024-02-03 00:00:00,32862,1980.0,1980,0,0,...,0,560,0,"brthyy, Year (e.g. 1967)",0,,,,0,0
6,28503,7107,2005200307,2023-11-13,2023-11-13 00:00:00,32862,0.0,0,45883771,0,...,0,230,0,"dmledu, How often would you say that you engage i",0,,,,0,0
7,151775,4067,2005200137,2024-01-03,2024-01-03 00:00:00,32862,3.0,3.0,2005200273,0,...,0,1170,0,"dri2, About how many miles did you personally dri",0,,,,0,0
8,245250,1085,2005200278,2023-10-11,2023-10-11 00:00:00,32862,0.0,0,45883771,0,...,0,1883,0,"dmlhex, How often would you say that you engage i",0,,,,0,0
9,212635,1141,40769032,2023-12-22,2023-12-22 00:00:00,32862,4.0,4,45879208,0,...,0,1629,0,"pxne4, There are sidewalks on most of the streets",0,,,,0,0

In [9]:
condition_occurrence_df.shape
#sum(condition_occurrence_df["condition_concept_id"] == 80502)

(5902, 16)

In [10]:
# Find concept IDs in measurement.csv
measurement_unique_values = measurement_df['measurement_source_value'].unique()
measurement_sorted_list = sorted(measurement_unique_values)
print(len(measurement_sorted_list))
measurement_concepts={}

for value in measurement_sorted_list:
    concept_id = measurement_df['measurement_concept_id'].get(measurement_df['measurement_source_value']==value).iloc[0]
    measurement_concepts[value] = concept_id
    print(f"'{value}': {concept_id},")

110
'A/G Ratio': 4288601,
'ALT (IU/L)': 3006923,
'AST (IU/L)': 3013721,
'Albumin (g/dL)': 3024561,
'Alkaline Phosphatase (IU/L)': 3035995,
'BUN (mg/dL)': 3013682,
'BUN/Creatinine ratio': 4112223,
'Bilirubin, Total (mg/dL)': 3024128,
'C-Peptide (ng/mL)': 3010084,
'CRP - HS (mg/L)': 3010156,
'Calcium (mg/dL)': 3006906,
'Carbon Dioxide, Total (mEq/L)': 3015632,
'Chloride (mEq/L)': 3014576,
'Creatinine (mg/dL)': 3016723,
'Globulin, Total (g/dL)': 3021886,
'Glucose (mg/dL)': 3004501,
'HDL Cholesterol (mg/dL)': 3007070,
'HbA1c (%)': 3004410,
'INSULIN (ng/mL)': 3016244,
'LDL Cholesterol Calculation (mg/dL)': 3028288,
'NT-proBNP (pg/mL)': 3029187,
'Potassium (mEq/L)': 3023103,
'Protein, Total (g/dL)': 3020630,
'Sodium (mEq/L)': 3019550,
'Total Cholesterol (mg/dL)': 3027114,
'Triglycerides (mg/dL)': 3022192,
'Troponin-T (ng/L)': 40769783,
'Urine Albumin (mg/dL)': 3001802,
'Urine Creatinine (mg/dL)': 3017250,
'bmi_vsorres, BMI': 4245997,
'bp1_diabp_vsorres, Diastolic (mmHg)': 3012888,
'bp1_sysbp_vsorres, Systolic (mmHg)': 3004249,
'bp2_diabp_vsorres, Diastolic (mmHg)': 3012888,
'bp2_sysbp_vsorres, Systolic (mmHg)': 3004249,
'clock_visuospatial_executive_time': 2005200347,
'cube_visuospatial_executive': 2005200345,
'cube_visuospatial_executive_time': 2005200346,
'delayed_recall_with_no_clue': 2005200365,
'delayed_recall_with_no_clue_time': 2005200366,
'digitspan_time': 2005200354,
'fluency_language': 2005200361,
'fluency_language_time': 2005200362,
'height_vsorres, Height (cm)': 3036277,
'hip_vsorres, Hip Circumference (cm)': 2005200153,
'lbscat_a1c, Hemoglobin - g/dL': 2005200184,
'lbscat_hct, Hematocrit  - %': 3009542,
'lbscat_mch, MCH - pg': 3035941,
'lbscat_mchc, MCHC - g/dL': 3003338,
'lbscat_mcv, MCV - fL': 3024731,
'lbscat_plt, Platelets - x10E3/µL': 3007461,
'lbscat_rbc, Red Blood Cells (RBC) - x10E6/µL': 2005200183,
'lbscat_rdw, RDW - %': 3002385,
'lbscat_wbc, White Blood Cells (WBC) - x10E3/µL': 2005200182,
'lettera': 2005200355,
'lettera_time': 2005200356,
'memory_trial1': 2005200350,
'memory_trial1_time': 2005200351,
'memory_trial2': 2005200352,
'memory_trial2_time': 2005200353,
'mlcsodfcl, OD: Value of final correct letter': 2005200486,
'mlcsodlog, OD: Log Contrast Sensitivity': 2005200552,
'mlcsodmiss, OD: Number of misses prior to stoppin': 2005200487,
'mlcsosfcl, OS: Value of final correct letter': 2005200488,
'mlcsoslog, OS: Log Contrast Sensitivity': 2005200553,
'mlcsosmiss, OS: Number of misses prior to stoppin': 2005200489,
'moca_abstraction': 2005200363,
'moca_abstraction_time': 2005200364,
'moca_combined_mis_score': 2005200370,
'moca_orientation': 2005200367,
'moca_orientation_time': 2005200368,
'moca_total_score': 37174522,
'msslffl, Left Foot - Felt:': 2005200161,
'mssrffl, Right Foot - Felt:': 2005200159,
'naming': 2005200348,
'naming_time': 2005200349,
'plcsodfcl, OD: Value of final correct letter': 2005200338,
'plcsodlog, OD: Log Contrast Sensitivity': 2005200155,
'plcsodmiss, OD: Number of misses prior to stoppin': 2005200339,
'plcsosfcl, OS: Value of final correct letter': 2005200340,
'plcsoslog, OS: Log Contrast Sensitivity': 2005200156,
'plcsosmiss, OS: Number of misses prior to stoppin': 2005200341,
'pulse_vsorres, Heart Rate (bpm)': 4239408,
'pulse_vsorres_2, Heart Rate (bpm)': 4239408,
'repetition': 2005200359,
'repetition_time': 2005200360,
'subtraction': 2005200357,
'subtraction_time': 2005200358,
'trails_visuospatial_executive': 4165596,
'trails_visuospatial_executive_time': 2005200344,
'viaodaxi, OD - Autorefractor - Axis': 3034190,
'viaodcyl, OD - Autorefractor - Cylinder': 3033346,
'viaodmlog, LLVA Letter Score - Mesopic VA - OD': 2005200056,
'viaodmscore, Mesopic LogMAR OD Score': 2005200336,
'viaodmsf, Snellen fraction - Mesopic VA - OD': 2005200054,
'viaodplog, VA Letter Score - Photopic VA - OD': 2005200042,
'viaodpscore, Photopic LogMAR OD Score': 2005200052,
'viaodpsf, Snellen fraction - Photopic VA - OD': 2005200012,
'viaodsph, OD - Autorefractor - Sphere': 3000744,
'viaosaxi, OS - Autorefractor - Axis': 3001254,
'viaoscyl, OS - Autorefractor - Cylinder': 3002343,
'viaosmlog, LLVA Letter Score - Mesopic VA - OS': 2005200057,
'viaosmscore, Mesopic LogMAR OS Score': 2005200337,
'viaosmsf, Snellen fraction - Mesopic VA - OS': 2005200055,
'viaosplog, VA Letter Score - Photopic VA - OS': 2005200043,
'viaospscore, Photopic LogMAR OS Score': 2005200053,
'viaospsf, Snellen fraction - Photopic VA - OS': 2005200013,
'viaossph, OS - Autorefractor - Sphere': 3003500,
'waist_vsorres, Waist Circumference (cm)': 2005200152,
'weight_vsorres, Weight (kilograms)': 3025315,
'whr_vsorres, Waist to Hip Ratio (WHR)': 44809433,

In [11]:
# Find concept IDs in condition.csv
condition_unique_values = condition_occurrence_df['condition_source_value'].unique()
condition_sorted_list = sorted(condition_unique_values)
print(len(condition_sorted_list))
for value in condition_sorted_list:
    concept_id = condition_occurrence_df['condition_concept_id'].get(condition_occurrence_df['condition_source_value']==value).iloc[0]
    print(f"'{value}': {concept_id},")

31
'mh_a1c, Elevated A1C levels (elevated blood sugar': 2005200547,
'mhoccur_ad, Dementia (Examples: Alzheimer's Disea': 4182210,
'mhoccur_amd, Age-related macular degeneration (AM': 374028,
'mhoccur_ca, Cancer (any type)': 4194405,
'mhoccur_circ, Circulation problems (Examples: art': 2005200015,
'mhoccur_clsh, High blood cholesterol': 4159131,
'mhoccur_cns, Other neurological conditions': 46271045,
'mhoccur_cogn, Mild cognitive impairment (known as': 439795,
'mhoccur_crt, Cataracts (in one or both eyes)': 4317977,
'mhoccur_cvdot, Other heart issues (Examples: pace': 2005200627,
'mhoccur_ded, Dry eye (in one or both eyes)': 4036620,
'mhoccur_ear, Hearing impairment': 439378,
'mhoccur_gi, Digestive problems (Examples: stomach': 4201745,
'mhoccur_glc, Glaucoma (in one or both eyes)': 437541,
'mhoccur_hbp, High blood pressure': 316866,
'mhoccur_lbp, Low blood pressure': 317002,
'mhoccur_mi, Heart attack': 4329847,
'mhoccur_ms, Multiple sclerosis': 374919,
'mhoccur_oa, Osteoporosis': 80502,
'mhoccur_obs, Obesity': 433736,
'mhoccur_pd, Parkinson's disease': 381270,
'mhoccur_pdr, Diabetic retinopathy (in one or both': 4174977,
'mhoccur_plm, Chronic pulmonary (lung) problems (E': 4186898,
'mhoccur_ra, Arthritis (joint pain)': 4291025,
'mhoccur_rnl, Kidney problems': 2005200017,
'mhoccur_rvo, Retinal vascular occlusion ("stroke ': 440392,
'mhoccur_strk, Stroke': 2005200628,
'mhoccur_ua, Urinary problems (Examples: urinary t': 81902,
'mhterm_dm2, Type II Diabetes': 201826,
'mhterm_predm, Pre-diabetes': 37018196,
'sumrjcdur, Do you use marijuana now?': 37116660,

In [12]:
# Find concept IDs in condition_occurrence.csv and observation.csv
if "condition_concept_id" in condition_occurrence_df.columns:
    condition_matches = condition_occurrence_df["condition_concept_id"].isin(observation_df["qualifier_concept_id"])
    matching_observations = observation_df[observation_df["qualifier_concept_id"].isin(condition_occurrence_df["condition_concept_id"])]

    used_rows = observation_df["qualifier_concept_id"].isin(matching_observations["qualifier_concept_id"])
    observation_remaining = observation_df[~used_rows]

In [13]:
observation_df.head()

,observation_id,person_id,observation_concept_id,observation_date,observation_datetime,observation_type_concept_id,value_as_number,value_as_string,value_as_concept_id,qualifier_concept_id,...,provider_id,visit_occurrence_id,visit_detail_id,observation_source_value,observation_source_concept_id,unit_source_value,qualifier_source_value,value_source_value,observation_event_id,obs_event_field_concept_id
0,44396,7353,2005200128,2024-06-21,2024-06-21 00:00:00,32862,1.0,1.0,36210226,0,...,0,355,0,"pxrd3, On a scale of 1-6, how stressful was this",0,,,,0,0
1,276196,1384,42528764,2024-07-31,2024-07-31 00:00:00,37161934,17.0,17.0,0,0,...,0,0,0,years_of_education,0,NaN,NaN,17.0,0,0
2,210536,1053,40766232,2023-10-10,2023-10-10 00:00:00,32862,18.0,18,45884155,0,...,0,1613,0,"pxed1, What is the highest grade or level of scho",0,,,,0,0
3,197490,1268,2005200504,2024-05-01,2024-05-01 00:00:00,32862,4.0,4.0,0,0,...,0,1513,0,"pxrd15, On a scale of 1-6, how stressful was this",0,,,,0,0
4,168986,4239,2005200014,2024-02-24,2024-02-24 00:00:00,32862,0.0,0.0,45878245,80502,...,0,1298,0,"mhoccur_oa, Osteoporosis",0,,Osteoporosis,,0,0

In [14]:
condition_unique_values = matching_observations['observation_source_value'].unique()
condition_sorted_list = sorted(condition_unique_values)
print(len(condition_sorted_list))
condition_concepts={}

for value in condition_sorted_list:
    concept_id = matching_observations['qualifier_concept_id'].get(matching_observations['observation_source_value']==value).iloc[0]
    condition_concepts[value] = concept_id
    print(f"'{value}': {concept_id},")

30
'mh_a1c, Elevated A1C levels (elevated blood sugar': 2005200547,
'mhoccur_ad, Dementia (Examples: Alzheimer's Disea': 4182210,
'mhoccur_amd, Age-related macular degeneration (AM': 374028,
'mhoccur_ca, Cancer (any type)': 4194405,
'mhoccur_circ, Circulation problems (Examples: art': 2005200015,
'mhoccur_clsh, High blood cholesterol': 4159131,
'mhoccur_cns, Other neurological conditions': 46271045,
'mhoccur_cogn, Mild cognitive impairment (known as': 439795,
'mhoccur_crt, Cataracts (in one or both eyes)': 4317977,
'mhoccur_cvdot, Other heart issues (Examples: pace': 2005200627,
'mhoccur_ded, Dry eye (in one or both eyes)': 4036620,
'mhoccur_ear, Hearing impairment': 439378,
'mhoccur_gi, Digestive problems (Examples: stomach': 4201745,
'mhoccur_glc, Glaucoma (in one or both eyes)': 437541,
'mhoccur_hbp, High blood pressure': 316866,
'mhoccur_lbp, Low blood pressure': 317002,
'mhoccur_mi, Heart attack': 4329847,
'mhoccur_ms, Multiple sclerosis': 374919,
'mhoccur_oa, Osteoporosis': 80502,
'mhoccur_obs, Obesity': 433736,
'mhoccur_pd, Parkinson's disease': 381270,
'mhoccur_pdr, Diabetic retinopathy (in one or both': 4174977,
'mhoccur_plm, Chronic pulmonary (lung) problems (E': 4186898,
'mhoccur_ra, Arthritis (joint pain)': 4291025,
'mhoccur_rnl, Kidney problems': 2005200017,
'mhoccur_rvo, Retinal vascular occlusion ("stroke ': 440392,
'mhoccur_strk, Stroke': 2005200628,
'mhoccur_ua, Urinary problems (Examples: urinary t': 81902,
'mhterm_dm2, Type II Diabetes': 201826,
'mhterm_predm, Pre-diabetes': 37018196,

In [15]:
observation_unique_values = observation_remaining['observation_source_value'].unique()
observation_sorted_list = sorted(observation_unique_values)
print(len(observation_sorted_list))
observation_concepts={}
for value in observation_sorted_list:
    concept_id = observation_remaining['observation_concept_id'].get(observation_remaining['observation_source_value']==value).iloc[0]
    observation_concepts[value]= concept_id
    
    print(f"'{value}': {concept_id},")

284
'age_years_at_interview': 2005200369,
'brthyy, Year (e.g. 1967)': 4078999,
'c184390_dat, Date paper consent completed': 4160030,
'cage, Age (in years)': 4265453,
'ces1, I was bothered by things that usually don't': 1761605,
'ces10, I could not "get going"': 1761073,
'ces2, I had trouble keeping my mind on what I was': 1761791,
'ces3, I felt depressed': 1761895,
'ces4, I felt that everything I did was an effort': 1761503,
'ces5, I felt hopeful about the future': 1761675,
'ces6, I felt fearful': 1761739,
'ces7, My sleep was restless': 1761695,
'ces8, I was happy': 1761700,
'ces9, I felt lonely': 1761319,
'cesmpdat, CES-D-10 survey date': 4160030,
'cesstartts, CES-D-10 Survey Started Timestamp (fr': 2005200558,
'cestl, CESD-10 Score': 1761347,
'cl_maristat, Marital Status': 4053609,
'clock_visuospatial_executive': 21492218,
'cm_act, Have you taken acetaminophen medicines, s': 2005200146,
'cm_ant, Have you taken antihistamines, such as co': 2005200148,
'cm_asp, Have you taken aspirin in the past 2 week': 2005200145,
'cm_dcg, Have you taken decongestants, such as col': 2005200149,
'cm_ibp, Have you taken ibuprofen or ibuprofen-con': 2005200147,
'cm_slp, Have you taken sleeping pills in the past': 2005200150,
'cmcmpdat, Date medications assessment conducted': 4260905,
'cmtrt_a1c, Do you take pills to control your A1C ': 2005200548,
'cmtrt_glcs, Do you use other injections to contro': 2005200550,
'cmtrt_insln, Do you inject insulin to control you': 2005200549,
'cmtrt_lfst, Do you use lifestyle changes to contr': 2005200004,
'diet1, How many times a week did you eat fast foo': 40771095,
'diet2, How many servings of fruit did you eat eac': 21493059,
'diet3, How many servings of vegetables did you ea': 21493061,
'diet4, How many regular sodas or glasses of sweet': 37311745,
'diet5, How many times a week did you eat beans (l': 2005200059,
'diet6, How many times a week did you eat regular ': 2005200060,
'diet7, How many times a week did you eat desserts': 2005200061,
'diet8, How much margarine, butter, or meat fat do': 2005200062,
'diet9, How many servings of fruit juice did you d': 2005200063,
'dietscore, Diet score': 2005200064,
'dietstartts, Dietary Survey Start Timestamp (from': 2005200558,
'digitspan': 4153980,
'dmgcmpdat, Demographic survey date (date survey/f': 4160030,
'dmgcmpts, Demograhics Survey Completed Timestamp ': 2005200559,
'dmgstartts, Demographics Survey Started Timestamp': 2005200558,
'dmlact, What would you consider your typical acti': 44808782,
'dmlcmpdat, Diabetes survey date': 4160030,
'dmlcmpts, Diabetes Survey Completed Timestamp (fr': 2005200559,
'dmledu, How often would you say that you engage i': 2005200307,
'dmlfeet, How often do you inspect your feet?': 2005200308,
'dmlfrveg, In a typical day, how many servings of ': 4295005,
'dmlgrain, In a typical day, how often do you cons': 2005200306,
'dmlhex, How often would you say that you engage i': 2005200278,
'dmlmd, Which of the following options best descri': 2005200309,
'dmlpor, When reflecting on your typical eating ha': 764035,
'dmlstartts, Diabetes Survey Started Timestamp (fr': 2005200558,
'dmlsugar, When reflecting on your typical eating ': 2005200305,
'dmlvex, In a typical week, how often do you engag': 2005200277,
'dri1, In an average week, how many days per week ': 2005200136,
'dri2, About how many miles did you personally dri': 2005200137,
'dricmpdat, Date driving record assessment conduct': 4260905,
'dvamwstdat, Date device given to participant': 4260905,
'dvenvstdat, Date device given to participant': 4260905,
'eos_ds, Did the subject complete the study?': 2005200192,
'eos_dsdecod, What was the primary reason the subj': 4260904,
'eos_dsstdat, What was the study discontinuation o': 4260905,
'eos_dsvst, Provide the last study visit/stage com': 3655035,
'faqcmpts, FAQ Survey Completed Timestamp (from RE': 2005200559,
'faqstartts, FAQ Survey Started Timestamp (from RE': 2005200558,
'fh_dm2pt, Were either of your parents diagnosed w': 2005200018,
'fh_dm2sb, Has a sibling been diagnosed with Type ': 2005200019,
'fh_dm2sbsp, If yes, please check all that apply:': 2005200464,
'food_insecurity_change_diet_frequency, How often ': 36660018,
'icfcmpts, Consent Survey Completed Timestamp': 2005200559,
'icfsvyts, Consent Survey Start Timestamp': 2005200558,
'lbdattim1, Date & time clinical labs performed': 4160030,
'mh_dm_age, If yes, at what age were you first dia': 4307859,
'mhcat_adot, If yes, please choose between:': 2005200014,
'mhcmpdat, Health survey date': 4160030,
'mhcmpts, Heath Survey Completed Timestamp (from R': 2005200559,
'mhoccur_fall, Have you fallen in the last 12 mont': 40757198,
'mhoccur_fallot, If so, how many times in the last': 4310026,
'mhoccur_yn, Have you been diagnosed with any cond': 2005200470,
'mhstartts, Health Survey Started Timestamp (from ': 2005200558,
'mhterm_dm1, Type I Diabetes': 2005200014,
'mlcscmpdat, Date procedure performed': 4160030,
'moca_total_score_time': 1988422,
'mocacmpdattim, Date time MoCA performed': 4160030,
'msscmpdat, Date monofilament performed': 4160030,
'paate, How many hours since you last ate? (number': 2005200151,
'pacmpdat, Date Assessment Performed --- Populated': 4160030,
'paid_cml, Coping with complications of diabetes': 2005200048,
'paid_dpr, Feeling depressed when you think about ': 2005200045,
'paid_eng, Feeling that diabetes is taking up too ': 2005200047,
'paid_scrd, Feeling scared when you think about li': 2005200044,
'paid_wr, Worrying about the future and the possib': 2005200046,
'paidcmpts, PAID-5 DM Survey Completed Timestamp (': 2005200559,
'paidscore, PAID score': 2005200049,
'paidstartts, PAID-5 DM Survey Start Timestamp (fr': 2005200558,
'pdrx9, On a scale of 1-6, how stressful was this ': 2005200498,
'plcscmpdat, Date procedure performed': 4160030,
'preconcmpdat, Pre-consent survey/form date (date ': 4160030,
'preconcmpts, Pre-consent Survey Completed Timesta': 2005200559,
'preconstartts, Pre-consent Survey Started Timesta': 2005200558,
'px011002_metadata, PhenX Education Attainment Met': 2005200102,
'px11502_metadata, PhenX Health Insurance MetaData': 2005200102,
'px270101_metadata, PhenX Health Care Access MetaD': 2005200102,
'px270201_metadata, PhenX English Proficiency Meta': 2005200102,
'px270301_metadata, PhenX MetaData': 2005200102,
'px280301_metadata, PhenX Job Security MetaData ': 2005200102,
'px280801_metadata, PhenX Prescriptions Affordabil': 2005200102,
'px280901_metadata, PhenX Healthcare Discriminatio': 2005200102,
'px281401_metadata, PhenX Housing Insecurity MetaD': 2005200102,
'px281501_metadata, PhenX Racial/Ethnic MetaData': 2005200102,
'pxahc1, About how long has it been since you last': 2005200090,
'pxahc10, During the past 12 months, was there any': 2005200099,
'pxahc2, Was this a wellness visit, physical, or g': 2005200091,
'pxahc3, About how long has it been since you last': 2005200092,
'pxahc4, Is there a place that you USUALLY go to i': 2005200093,
'pxahc5, What kind of place is it/do you go to mos': 2005200094,
'pxahc6, During the past 12 months, how many times': 2005200095,
'pxahc7, During the past 12 months, how many times': 2005200096,
'pxahc8, During the past 12 months, have you been ': 2005200097,
'pxahc9, During the past 12 months, have you DELAY': 2005200098,
'pxdhc1, You are treated with less courtesy than o': 40770200,
'pxdhc2, You are treated with less respect than ot': 40770201,
'pxdhc3, You receive poorer service than others.': 40192503,
'pxdhc4, A doctor or nurse acts as if he or she th': 40192505,
'pxdhc5, A doctor or nurse acts as if he or she is': 40192423,
'pxdhc6, A doctor or nurse acts as if he or she is': 40192383,
'pxdhc7, You feel like a doctor or nurse is not li': 40192394,
'pxed1, What is the highest grade or level of scho': 40766232,
'pxep1, Is English your first language?': 40757199,
'pxep2, Do you speak another language at home?': 2005200480,
'pxep3, Since you speak a language other than Engl': 40769340,
'pxfi1, The first statement is, "The food that (I/': 36306143,
'pxfi2, "(I/we) couldn't afford to eat balanced me': 36660487,
'pxfi3, In the last year, did you and/or other adu': 36660433,
'pxfi4, In the last 12 months, did you ever eat le': 36659800,
'pxfi5, In the last 12 months, were you ever hungr': 36660509,
'pxfistartts, PhenX Food Insecurity Survey Started': 2005200558,
'pxhi1, What is your living situation today?': 2005200075,
'pxhic1, Insurance through a current or former emp': 2005200081,
'pxhic2, Insurance purchased directly from an insu': 2005200082,
'pxhic3, Medicare, for people 65 and older, or peo': 2005200083,
'pxhic4, Medicaid, Medical Assistance (MA), the Ch': 2005200084,
'pxhic5, TRICARE or other military health care, in': 2005200085,
'pxhic7, Any other type of health insurance covera': 2005200087,
'pxhic8, Does this mean you currently have no heal': 2005200088,
'pxji1, Thinking about the next 12 months, how lik': 2005200073,
'pxji2, About how easy would it be for you to find': 2005200074,
'pxne1, What is the main type of housing in your n': 40769029,
'pxne10, There are many interesting things to look': 2005200115,
'pxne11, How many motor vehicles in working order ': 2005200116,
'pxne12, There are many four-way intersections in ': 2005200117,
'pxne13, The sidewalks in my neighborhood are well': 2005200118,
'pxne14, Places for bicycling (such as bike paths)': 2005200119,
'pxne15, There is so much traffic on the streets t': 2005200120,
'pxne16, The crime rate in my neighborhood makes i': 2005200121,
'pxne17, There are many places to go within easy w': 2005200122,
'pxne2, Many shops, stores, markets or other place': 40769030,
'pxne3, It is within a 10-15 minute walk to a tran': 40769031,
'pxne4, There are sidewalks on most of the streets': 40769032,
'pxne5, There are facilities to bicycle in or near': 40769033,
'pxne6, My neighborhood has several free or low co': 40769034,
'pxne7, The crime rate in my neighborhood makes it': 40769035,
'pxne8, There is so much traffic on the streets th': 2005200113,
'pxne9, I see many people being physically active ': 2005200114,
'pxnecmpts, PhenX Neighborhood Environment Survey ': 2005200559,
'pxnestartts, PhenX Neighborhood Enviroment Survey': 2005200558,
'pxpa1, In the last 12 months, have you delayed ge': 2005200077,
'pxpa2, Did any other person in your household del': 2005200078,
'pxpa3, In the last 12 months, was there any time ': 2005200079,
'pxpa4, In the last 12 months, was there any time ': 2005200080,
'pxrd1, How often in the past year?': 2005200126,
'pxrd10, How often in the past year?': 2005200499,
'pxrd11, How often in your entire life?': 2005200500,
'pxrd12, On a scale of 1-6, how stressful was this': 2005200501,
'pxrd13, How often in the past year?': 2005200502,
'pxrd14, How often in your entire life?': 2005200503,
'pxrd15, On a scale of 1-6, how stressful was this': 2005200504,
'pxrd16, How often in the past year?': 2005200505,
'pxrd17, How often in your entire life?': 2005200506,
'pxrd18, On a scale of 1-6, how stressful was this': 2005200507,
'pxrd19, How often in the past year?': 2005200508,
'pxrd2, How often in your entire life?': 2005200127,
'pxrd20, How often in your entire life?': 2005200509,
'pxrd21, On a scale of 1-6, how stressful was this': 2005200510,
'pxrd22, How often in the past year?': 2005200511,
'pxrd23, How often in your entire life?': 2005200512,
'pxrd24, On a scale of 1-6, how stressful was this': 2005200513,
'pxrd25, How often in the past year?': 2005200514,
'pxrd26, How often in your entire life?': 2005200515,
'pxrd27, On a scale of 1-6, how stressful was this': 2005200516,
'pxrd28, How often in the past year?': 2005200517,
'pxrd29, How often in your entire life?': 2005200518,
'pxrd3, On a scale of 1-6, how stressful was this ': 2005200128,
'pxrd30, On a scale of 1-6, how stressful was this': 2005200519,
'pxrd31, How often in the past year?': 2005200520,
'pxrd32, How often in your entire life?': 2005200521,
'pxrd33, On a scale of 1-6, how stressful was this': 2005200522,
'pxrd34, How often in the past year?': 2005200523,
'pxrd35, How often in your entire life?': 2005200524,
'pxrd36, On a scale of 1-6, how stressful was this': 2005200525,
'pxrd37, How often in the past year?': 2005200526,
'pxrd38, How often in your entire life?': 2005200527,
'pxrd39, On a scale of 1-6, how stressful was this': 2005200528,
'pxrd4, How often in the past year?': 2005200493,
'pxrd40, How often in the past year?': 2005200529,
'pxrd41, How often in your entire life?': 2005200530,
'pxrd42, On a scale of 1-6, how stressful was this': 2005200531,
'pxrd43, How often in the past year?': 2005200532,
'pxrd44, How often in your entire life?': 2005200533,
'pxrd45, On a scale of 1-6, how stressful was this': 2005200534,
'pxrd46, How often in the past year?': 2005200535,
'pxrd47, How often in your entire life?': 2005200536,
'pxrd48, On a scale of 1-6, how stressful was this': 2005200537,
'pxrd49, How often in the past year?': 2005200538,
'pxrd5, How often in your entire life?': 2005200494,
'pxrd50, How often in your entire life?': 2005200539,
'pxrd51, On a scale of 1-6, how stressful was this': 2005200540,
'pxrd52, In the Past Year?': 2005200541,
'pxrd53, In your entire life?': 2005200542,
'pxrd54, On a scale of 1-6, how stressful was this': 2005200543,
'pxrd6, On a scale of 1-6, how stressful was this ': 2005200495,
'pxrd7, How often in the past year?': 2005200496,
'pxrd8, How often in your entire life?': 2005200497,
'pxrdcmpdat, PhenX Racial/Ethnic Discrimination su': 4160030,
'pxrdcmpts, PhenX Racial/Ethnic Discrimination Sur': 2005200558,
'pxrdstartts, PhenX Racial/Ethnic Discrimination S': 2005200559,
'pxsdohcmpdat, PhenX SDOH survey date': 4160030,
'pxsdohstartts, PhenX SDOH Survey Started Timestam': 2005200558,
'pxsficmpdat, PhenX Food Insecurity survey date': 4160030,
'pxsficmpts, PhenX Food Insecurity Survey Complete': 2005200559,
'reccmpdat, Recruitment survey date (date survey/f': 3039611,
'reccmpts, Recruitment Survey Completed Timestamp ': 2005200559,
'recstartts, Recruitment Survey Started Timestamp ': 2005200558,
'scrcmpdat, Screening survey date (date survey/for': 4160030,
'scrcmpts, Screening Survey Completed Timestamp (f': 2005200559,
'scrstartts, Screening Survey Started Timestamp (f': 2005200558,
'studyid, Participant Study ID': 44786673,
'sualcage, At what age did you start drinking alco': 40766301,
'sualcdrv, Do you drive after having a drink, even': 2005200030,
'sualckncf, Have you ever consumed alcohol?': 40772145,
'subrdosfr, During the average week, how many 12 o': 2005200025,
'subrkncf, Have you had any beer or ale in the pas': 2005200024,
'sucmpdat, Substance use survey date': 4160030,
'sucmpts, Substance Use Survey Completed Timestamp': 2005200559,
'sulqdosfr, During the average week, how many 1.5 ': 2005200029,
'sulqkncf, Have you had any liquor in the past yea': 2005200028,
'sumrjcdur, Do you use marijuana now?': 2005200473,
'sumrjceddur, How many total years have you used m': 2005200038,
'sumrjfr, When you used marijuana, approximately h': 2005200039,
'sumrjkncf, Have you ever used marijuana (cannabis': 2005200036,
'sumrjstage, At what age did you start using marij': 37020592,
'sumrjtrt, In what form do you usually use marijua': 2005200037,
'susmkcdur, Do you smoke now?': 40766945,
'susmkdosfr, On average how many cigarettes do/did': 40769208,
'susmkncf, Have you smoked at least 100 cigarettes': 40766306,
'susmkstaage, At what age did you start smoking? (': 40770348,
'susmkstoage, How many total years have you smoked': 40770349,
'sustartts, Substance Use Survey Started Timestamp': 2005200558,
'suvpcdur, Do you vape or use e-cigarettes now?': 2005200033,
'suvpdosfr, When you vaped or used e-cigarettes, a': 2005200035,
'suvpkncf1, Have you ever vaped or used e-cigarett': 2005200031,
'suvpstage, At what age did you start vaping or us': 2005200032,
'suvptoage, How many total years have you vaped or': 2005200034,
'suvptoyr, How many total years have you consumed ': 44786670,
'suwndosfr, During the average week, how many 5 oz': 2005200027,
'suwnkncf, Have you had any wine in the past year?': 2005200026,
'test_upload_date': 3006440,
'via1, How much difficulty, if any, do you have in': 2005200067,
'via2, How much difficulty, if any, do you have re': 2005200068,
'via3, Because of your eyesight, how much difficul': 40768765,
'via4, When was the last time you had your eyes ex': 40758529,
'via5, You have indicated that you have not seen a': 2005200069,
'via6, When was the last time you had an eye exam ': 2005200070,
'viacmpdat, Ophthalmic survey date': 4160030,
'viacmpts, Ophthalmic Survey Completed Timestamp (': 2005200559,
'viaocmpdat, Date BCVA performed': 4160030,
'viaomthd, Method used to complete form': 2005200011,
'viastartts, Ophthalmic Survey Started Timestamp (': 2005200558,
'visdat, Planned date & time of in-person visit': 4260905,
'years_of_education': 42528764,

In [16]:
print(len(observation_concepts))

284

# How to make csv files for analyzing

### Example of making csv file by using variables listed in measurement.csv

In [17]:
# Put variables you want to add as dictionary mapping concept names to their respective concept IDs


# 59
def parse_measurement(df, concept_id):
    temp_df = df[df['measurement_concept_id'] == concept_id]
    return temp_df


measurement_out_df = pd.DataFrame(columns=['participant_id', 'age', 'study_group', 'clinical_site'])

measurement_out_df['participant_id'] = participants_df['participant_id']
measurement_out_df['age'] = participants_df['age']
measurement_out_df['study_group'] = participants_df['study_group']
measurement_out_df['clinical_site'] = participants_df['clinical_site']

for key, value in measurement_concepts.items():
    temp_df = parse_measurement(measurement_df, value)
    temp_df = temp_df.rename(columns={'value_as_number': key})
    temp_df = temp_df.rename(columns={'person_id': 'participant_id'})
    temp_df = temp_df[['participant_id', key]]
    # Average duplicate values
    dupes = temp_df[temp_df.duplicated('participant_id', keep=False)]
    temp_df = temp_df.groupby('participant_id', as_index=False).mean()
 
    measurement_out_df = pd.merge(measurement_out_df, temp_df, on='participant_id', how='left')

measurement_out_df = measurement_out_df.drop_duplicates(subset='participant_id', keep='last')
measurement_out_df.shape
measurement_out_df.head()
print(measurement_out_df.shape)
measurement_out_df.head()
print(measurement_out_df.isna().sum().sort_values(ascending=False).head())
measurement_out_df = measurement_out_df.fillna(measurement_out_df.median(numeric_only=True))
measurement_out_df.isna().sum().sort_values(ascending=False).head()

#print(final_df.shape)

(1067, 114)
C-Peptide (ng/mL)                43
HbA1c (%)                        43
INSULIN (ng/mL)                  43
Carbon Dioxide, Total (mEq/L)    41
Calcium (mg/dL)                  41
dtype: int64

participant_id    0
age               0
study_group       0
clinical_site     0
A/G Ratio         0
dtype: int64

In [18]:
from data_processing import handle_sentinels, drop_unbalanced_columns, bin_frame
measurement_out_df= handle_sentinels(measurement_out_df)
measurement_out_df = drop_unbalanced_columns(measurement_out_df, thresh=50)
measurement_out_df = bin_frame(measurement_out_df, skip_columns=['participant_id'], num_bins =16, alpha=3)

viaodsph, OD - Autorefractor - Sphere
viaossph, OS - Autorefractor - Sphere

In [19]:
# only bring in the three columns you want from df_new
to_add = participants_df[["participant_id", "study_group", "recommended_split"]]
measurement_out_df.drop(columns=["study_group"],  inplace=True)
measurement_out_df = pd.merge(
    measurement_out_df,
    to_add,
    on='participant_id',
    how='left'          # keeps all rows of final_df, and adds matching df_new cols
)

print(measurement_out_df.shape)    # should be (1067, original_cols+2)
measurement_out_df.head()
measurement_out_df.isna().sum()
measurement_out_df.head()

(1067, 113)

,participant_id,age,clinical_site,A/G Ratio,ALT (IU/L),AST (IU/L),Albumin (g/dL),Alkaline Phosphatase (IU/L),BUN (mg/dL),BUN/Creatinine ratio,...,"viaosmscore, Mesopic LogMAR OS Score","viaosmsf, Snellen fraction - Mesopic VA - OS","viaosplog, VA Letter Score - Photopic VA - OS","viaospscore, Photopic LogMAR OS Score","viaospsf, Snellen fraction - Photopic VA - OS","waist_vsorres, Waist Circumference (cm)","weight_vsorres, Weight (kilograms)","whr_vsorres, Waist to Hip Ratio (WHR)",study_group,recommended_split
0,1001,9,UW,12,1,4,10,5,6,9,...,5,1,11,3,0,3,2,2,pre_diabetes_lifestyle_controlled,train
1,1002,9,UW,5,4,7,9,6,3,5,...,10,4,7,8,2,8,7,9,healthy,train
2,1003,14,UW,7,3,3,9,5,5,7,...,5,1,11,3,0,8,4,11,oral_medication_and_or_non_insulin_injectable_...,train
3,1004,7,UW,11,3,1,8,10,4,7,...,15,9,0,15,8,6,5,7,oral_medication_and_or_non_insulin_injectable_...,val
4,1005,6,UW,5,4,6,6,8,4,4,...,7,2,8,7,2,5,5,7,insulin_dependent,val

In [20]:
measurement_out_df.head()
measurement_out_df.to_csv("measurements_all_binned.csv")

In [21]:
# Define mapping of condition_source_value → condition_concept_id


# Start from participants_df
condition_out_df = pd.DataFrame()
condition_out_df['participant_id'] = participants_df['participant_id']
condition_out_df['age'] = participants_df['age']
condition_out_df['study_group'] = participants_df['study_group']
condition_out_df['clinical_site'] = participants_df['clinical_site']

# Add binary columns for each condition
for cond_label, concept_id in condition_concepts.items():
    condition_patients = condition_occurrence_df[
        condition_occurrence_df['condition_concept_id'] == concept_id
    ][['person_id']].drop_duplicates()
    
    condition_patients[cond_label] = 1
    condition_patients = condition_patients.rename(columns={'person_id': 'participant_id'})
    
    condition_out_df = condition_out_df.merge(condition_patients, on='participant_id', how='left')

# Fill NaNs (no condition) with 0
condition_out_df[list(condition_concepts.keys())] = condition_out_df[list(condition_concepts.keys())].fillna(0).astype(int)

# Preview
print(condition_out_df.shape)
condition_out_df.head()
condition_out_df.isna().sum().head(30)

(1067, 34)

participant_id                                       0
age                                                  0
study_group                                          0
clinical_site                                        0
mh_a1c, Elevated A1C levels (elevated blood sugar    0
mhoccur_ad, Dementia (Examples: Alzheimer's Disea    0
mhoccur_amd, Age-related macular degeneration (AM    0
mhoccur_ca, Cancer (any type)                        0
mhoccur_circ, Circulation problems (Examples: art    0
mhoccur_clsh, High blood cholesterol                 0
mhoccur_cns, Other neurological conditions           0
mhoccur_cogn, Mild cognitive impairment (known as    0
mhoccur_crt, Cataracts (in one or both eyes)         0
mhoccur_cvdot, Other heart issues (Examples: pace    0
mhoccur_ded, Dry eye (in one or both eyes)           0
mhoccur_ear, Hearing impairment                      0
mhoccur_gi, Digestive problems (Examples: stomach    0
mhoccur_glc, Glaucoma (in one or both eyes)          0
mhoccur_hbp, High blood pressure                     0
mhoccur_lbp, Low blood pressure                      0
mhoccur_mi, Heart attack                             0
mhoccur_ms, Multiple sclerosis                       0
mhoccur_oa, Osteoporosis                             0
mhoccur_obs, Obesity                                 0
mhoccur_pd, Parkinson's disease                      0
mhoccur_pdr, Diabetic retinopathy (in one or both    0
mhoccur_plm, Chronic pulmonary (lung) problems (E    0
mhoccur_ra, Arthritis (joint pain)                   0
mhoccur_rnl, Kidney problems                         0
mhoccur_rvo, Retinal vascular occlusion ("stroke     0
dtype: int64

In [22]:
condition_out_df.to_csv("conditions_all.csv")

### Example of making csv file by using variables listed in observation.csv (and condition_occurance.csv)
Variables in condition_occurance.csv is overlapped to observation.csv.

In [23]:


observation_out_df = pd.DataFrame(columns=['participant_id', 'age', 'study_group', 'clinical_site'])

observation_out_df['participant_id'] = participants_df['participant_id']
observation_out_df['age'] = participants_df['age']
observation_out_df['study_group'] = participants_df['study_group']
observation_out_df['clinical_site'] = participants_df['clinical_site']

In [24]:

def parse_observation(df, concept_id):
    temp_df = df[df['observation_concept_id'] == concept_id]
    return temp_df
cnt = 0
for key, value in observation_concepts.items():
   # print(key, value)
    temp_df = parse_observation(observation_df, value)
    temp_df = temp_df.rename(columns={'value_as_number': key})
    temp_df = temp_df.rename(columns={'person_id': 'participant_id'})
    temp_df = temp_df[['participant_id', key]]
    temp_df = (
    temp_df.sort_values(by=key, na_position='last')
            .drop_duplicates(subset='participant_id', keep='first')
    )    
    if temp_df.shape[0] > 950 and temp_df.shape[0]<=1067:
        cnt = cnt+1
        observation_out_df = pd.merge(observation_out_df, temp_df, on='participant_id', how='left')
  
observation_out_df = observation_out_df.drop_duplicates(subset='participant_id', keep='last')
print(observation_out_df.shape) 
print(cnt)

(1067, 201)
197

In [25]:
observation_out_df.isna().sum().head(30)

participant_id                                          0
age                                                     0
study_group                                             0
clinical_site                                           0
age_years_at_interview                                  7
brthyy, Year (e.g. 1967)                                0
c184390_dat, Date paper consent completed            1067
cage, Age (in years)                                    0
ces1, I was bothered by things that usually don't       1
ces10, I could not "get going"                          2
ces2, I had trouble keeping my mind on what I was       4
ces3, I felt depressed                                  2
ces4, I felt that everything I did was an effort        1
ces5, I felt hopeful about the future                   6
ces6, I felt fearful                                    5
ces7, My sleep was restless                             4
ces8, I was happy                                       0
ces9, I felt lonely                                     6
cesmpdat, CES-D-10 survey date                       1067
cesstartts, CES-D-10 Survey Started Timestamp (fr    1067
cestl, CESD-10 Score                                    0
cl_maristat, Marital Status                          1059
clock_visuospatial_executive                            7
cm_act, Have you taken acetaminophen medicines, s      21
cm_ant, Have you taken antihistamines, such as co      21
cm_asp, Have you taken aspirin in the past 2 week      21
cm_dcg, Have you taken decongestants, such as col      20
cm_ibp, Have you taken ibuprofen or ibuprofen-con      22
cm_slp, Have you taken sleeping pills in the past      19
cmcmpdat, Date medications assessment conducted      1067
dtype: int64

In [26]:
sums = observation_out_df.isna().sum()
nan_cols_to_drop = []
for col in observation_out_df.columns:
    x = observation_out_df[col].isna().sum()
    if(x>=100):
        nan_cols_to_drop.append(col) 
print(nan_cols_to_drop)
observation_out_df = observation_out_df.drop(nan_cols_to_drop, axis=1)
observation_out_df = observation_out_df.fillna(observation_out_df.median(numeric_only=True))

['c184390_dat, Date paper consent completed', 'cesmpdat, CES-D-10 survey date', 'cesstartts, CES-D-10 Survey Started Timestamp (fr', 'cl_maristat, Marital Status', 'cmcmpdat, Date medications assessment conducted', 'dietscore, Diet score', 'dietstartts, Dietary Survey Start Timestamp (from', 'dmgcmpdat, Demographic survey date (date survey/f', 'dmgcmpts, Demograhics Survey Completed Timestamp ', 'dmgstartts, Demographics Survey Started Timestamp', 'dmlcmpdat, Diabetes survey date', 'dmlcmpts, Diabetes Survey Completed Timestamp (fr', 'dmlstartts, Diabetes Survey Started Timestamp (fr', 'dricmpdat, Date driving record assessment conduct', 'dvamwstdat, Date device given to participant', 'dvenvstdat, Date device given to participant', 'eos_dsstdat, What was the study discontinuation o', 'faqcmpts, FAQ Survey Completed Timestamp (from RE', 'faqstartts, FAQ Survey Started Timestamp (from RE', 'icfcmpts, Consent Survey Completed Timestamp', 'icfsvyts, Consent Survey Start Timestamp', 'lbdattim1, Date & time clinical labs performed', 'mhcmpdat, Health survey date', 'mhcmpts, Heath Survey Completed Timestamp (from R', 'mhstartts, Health Survey Started Timestamp (from ', 'mlcscmpdat, Date procedure performed', 'mocacmpdattim, Date time MoCA performed', 'msscmpdat, Date monofilament performed', 'pacmpdat, Date Assessment Performed --- Populated', 'paidcmpts, PAID-5 DM Survey Completed Timestamp (', 'paidstartts, PAID-5 DM Survey Start Timestamp (fr', 'plcscmpdat, Date procedure performed', 'preconcmpdat, Pre-consent survey/form date (date ', 'preconcmpts, Pre-consent Survey Completed Timesta', 'preconstartts, Pre-consent Survey Started Timesta', 'px011002_metadata, PhenX Education Attainment Met', 'px11502_metadata, PhenX Health Insurance MetaData', 'px270101_metadata, PhenX Health Care Access MetaD', 'px270201_metadata, PhenX English Proficiency Meta', 'px270301_metadata, PhenX MetaData', 'px280301_metadata, PhenX Job Security MetaData\xa0', 'px280801_metadata, PhenX Prescriptions Affordabil', 'px280901_metadata, PhenX Healthcare Discriminatio', 'px281401_metadata, PhenX Housing Insecurity MetaD', 'px281501_metadata, PhenX Racial/Ethnic MetaData', 'pxfistartts, PhenX Food Insecurity Survey Started', 'pxnecmpts, PhenX Neighborhood Environment Survey ', 'pxnestartts, PhenX Neighborhood Enviroment Survey', 'pxrdcmpdat, PhenX Racial/Ethnic Discrimination su', 'pxrdcmpts, PhenX Racial/Ethnic Discrimination Sur', 'pxrdstartts, PhenX Racial/Ethnic Discrimination S', 'pxsdohcmpdat, PhenX SDOH survey date', 'pxsdohstartts, PhenX SDOH Survey Started Timestam', 'pxsficmpdat, PhenX Food Insecurity survey date', 'pxsficmpts, PhenX Food Insecurity Survey Complete', 'reccmpdat, Recruitment survey date (date survey/f', 'reccmpts, Recruitment Survey Completed Timestamp ', 'recstartts, Recruitment Survey Started Timestamp ', 'scrcmpdat, Screening survey date (date survey/for', 'scrcmpts, Screening Survey Completed Timestamp (f', 'scrstartts, Screening Survey Started Timestamp (f', 'sucmpdat, Substance use survey date', 'sucmpts, Substance Use Survey Completed Timestamp', 'sustartts, Substance Use Survey Started Timestamp', 'viacmpdat, Ophthalmic survey date', 'viacmpts, Ophthalmic Survey Completed Timestamp (', 'viaocmpdat, Date BCVA performed', 'viastartts, Ophthalmic Survey Started Timestamp (', 'visdat, Planned date & time of in-person visit']

In [27]:
observation_out_df= handle_sentinels(observation_out_df)
observation_out_df = drop_unbalanced_columns(observation_out_df, thresh=50)
observation_out_df = bin_frame(observation_out_df, skip_columns=['participant_id'], num_bins =16, alpha=3)

age_years_at_interview
mhcat_adot, If yes, please choose between:
mhterm_dm1, Type I Diabetes
pxfi5, In the last 12 months, were you ever hungr
test_upload_date

In [28]:
common_cols = measurement_out_df.columns.intersection(condition_out_df.columns)
print("Common columns between observation_df and measurement_df:")
print(common_cols.tolist())

Common columns between observation_df and measurement_df:
['participant_id', 'age', 'clinical_site', 'study_group']

In [29]:
observation_out_df.isna().sum().sum()
print(observation_out_df.shape)

(1067, 127)

In [30]:
observation_out_df.to_csv("observations_all_binned.csv")

In [31]:
# Now merge all three data-frames drop age, clinical site and study group in all except measurement_out_df
cols_to_drop = [ 'age', 'clinical_site', 'study_group']
measurement_out_df.drop(columns = cols_to_drop, inplace=True)
observation_out_df.drop(columns = cols_to_drop, inplace=True)
print(measurement_out_df.shape)
print(condition_out_df.shape)
print(observation_out_df.shape)
all_feat_df = (
    condition_out_df
    .merge(measurement_out_df, on='participant_id', how='outer')
    .merge(observation_out_df, on='participant_id', how='outer')
)

print(all_feat_df.shape)
all_feat_df.to_csv("all_features_all_patients_binned.csv")

(1067, 110)
(1067, 34)
(1067, 124)
(1067, 266)